//! Memory store abstraction layer.
//!
//! Provides the MemoryStore trait and associated types (Memory, CreateMemory, SearchFilter, etc.)
//! for CRUD operations on memories. The PostgreSQL implementation lives in `postgres.rs`.
//! All intelligence/ and pipeline/ modules depend on types exported here.

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use pgvector::Vector;
use serde::{Deserialize, Serialize};

use crate::errors::MemcpError;

pub mod postgres;

/// Represents a stored memory with all rich metadata fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Memory {
    /// Unique identifier (UUID v4)
    pub id: String,
    /// The actual memory content
    pub content: String,
    /// Classification hint: "fact", "preference", "instruction", etc.
    pub type_hint: String,
    /// Origin source: "user", "assistant", "system", etc.
    pub source: String,
    /// Optional tags for categorization (stored as JSONB in PostgreSQL)
    pub tags: Option<serde_json::Value>,
    /// When the memory was created
    pub created_at: DateTime<Utc>,
    /// When the memory was last modified
    pub updated_at: DateTime<Utc>,
    /// When the memory was last accessed via get()
    pub last_accessed_at: Option<DateTime<Utc>>,
    /// Number of times memory has been retrieved
    pub access_count: i64,
    /// Embedding generation status: "pending", "complete", or "failed"
    /// Use EmbeddingStatus enum (in embedding module) for type-safe pipeline logic.
    pub embedding_status: String,
    /// Extracted named entities from content (JSONB array of strings, populated by extraction pipeline)
    pub extracted_entities: Option<serde_json::Value>,
    /// Extracted facts from content (JSONB array of strings, populated by extraction pipeline)
    pub extracted_facts: Option<serde_json::Value>,
    /// Extraction pipeline status: "pending", "complete", "failed", "skipped"
    pub extraction_status: String,
    /// When true, this memory was superseded by consolidation — suppress from search results
    pub is_consolidated_original: bool,
    /// ID of the consolidated memory this was merged into (None if not consolidated)
    pub consolidated_into: Option<String>,
    /// Actor who created this memory (optional until auth wired in Phase 12)
    pub actor: Option<String>,
    /// Actor type: "agent", "user", "system", "auto-store"
    pub actor_type: String,
    /// Audience scope: "global", "self", "tenant"
    pub audience: String,
    /// When the memory content refers to a specific point in time (e.g., "in 2019", "when I was 6").
    /// Separate from created_at — this is the event time embedded in the content, not the store time.
    pub event_time: Option<DateTime<Utc>>,
    /// Precision of event_time: "decade", "year", "month", "day"
    pub event_time_precision: Option<String>,
    /// Project scope. None means global (visible in all projects).
    /// Project-scoped searches return both project-scoped AND global (None) memories.
    pub project: Option<String>,
    /// Trust level: 0.0 (untrusted) to 1.0 (fully trusted).
    /// System-inferred from source/actor_type if not explicitly set at store time.
    pub trust_level: f32,
    /// Session identifier linking this memory to a specific agent session.
    pub session_id: Option<String>,
    /// Role of the agent that created this memory (e.g., "coder", "reviewer", "planner").
    pub agent_role: Option<String>,
    /// How this memory was created: "session_summary", "explicit_store", "annotation", "import".
    pub write_path: Option<String>,
    /// Extensible metadata JSONB (trust_history, annotations, etc.).
    pub metadata: serde_json::Value,
    /// L0 abstract: single concise sentence (~100 tokens) for semantic search.
    /// Generated by the abstraction pipeline. None if not yet generated or skipped.
    pub abstract_text: Option<String>,
    /// L1 overview: structured summary in 3-5 bullet points (~500 tokens).
    /// Generated by the abstraction pipeline when generate_overview = true.
    pub overview_text: Option<String>,
    /// Abstraction pipeline status: "pending", "complete", "failed", "skipped".
    /// "skipped" = content too short (< 200 chars) — abstraction adds no value.
    pub abstraction_status: String,
    /// Knowledge tier: "raw", "imported", "explicit", "derived", "pattern".
    /// Inferred from write_path at store time; caller can override. Per D-03.
    pub knowledge_tier: String,
    /// Source memory IDs (JSONB array of UUID strings).
    /// Required non-empty when tier = "derived" (D-04). Optional for "pattern". Null for others.
    pub source_ids: Option<serde_json::Value>,
    /// D-16: conversation-threading link. None for non-reply memories. (Phase 24.75 dropped
    /// the separate parent_id/chunking column; reply_to_id is the only threading link.)
    pub reply_to_id: Option<String>,
}

/// Input type for creating a new memory.
///
/// The store generates id, timestamps, and access_count.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateMemory {
    /// The memory content (required)
    pub content: String,
    /// Classification hint (default: "fact")
    #[serde(default = "default_type_hint")]
    pub type_hint: String,
    /// Origin source (default: "default")
    #[serde(default = "default_source")]
    pub source: String,
    /// Optional tags for categorization
    pub tags: Option<Vec<String>>,
    /// Optional timestamp override. When set, the store uses this instead of Utc::now().
    /// Used by benchmark harness for ingesting historical sessions.
    #[serde(default)]
    pub created_at: Option<DateTime<Utc>>,
    /// Actor who created this memory (optional until auth wired)
    pub actor: Option<String>,
    /// Actor type: "agent" (default), "user", "system", "auto-store"
    #[serde(default = "default_actor_type")]
    pub actor_type: String,
    /// Audience scope: "global" (default), "self", "tenant"
    #[serde(default = "default_audience")]
    pub audience: String,
    /// Optional caller-provided idempotency key for at-most-once store semantics.
    /// Repeated calls with the same key return the original memory (first wins).
    /// When absent, content-hash dedup applies within the configured window.
    #[serde(default)]
    pub idempotency_key: Option<String>,
    /// Optional event time extracted from content during store (e.g., "in 2019" → 2019-01-01T00:00:00Z).
    /// Populated by temporal extraction pipeline; None if no temporal reference found.
    #[serde(default)]
    pub event_time: Option<DateTime<Utc>>,
    /// Precision of event_time: "decade", "year", "month", "day"
    #[serde(default)]
    pub event_time_precision: Option<String>,
    /// Project scope for this memory. None means global (no project isolation).
    #[serde(default)]
    pub project: Option<String>,
    /// Explicit trust level override. None = system infers from source/actor_type.
    #[serde(default)]
    pub trust_level: Option<f32>,
    /// Session identifier linking this memory to a specific agent session.
    #[serde(default)]
    pub session_id: Option<String>,
    /// Role of the agent that created this memory (e.g., "coder", "reviewer", "planner").
    #[serde(default)]
    pub agent_role: Option<String>,
    /// How this memory was created: "session_summary", "explicit_store", "annotation", "import".
    #[serde(default)]
    pub write_path: Option<String>,
    /// Optional knowledge tier override. None = inferred from write_path (D-01).
    /// Valid values: "raw", "imported", "explicit", "derived", "pattern".
    #[serde(default)]
    pub knowledge_tier: Option<String>,
    /// Provenance source memory IDs. Required (non-empty) when knowledge_tier = "derived" (D-04).
    #[serde(default)]
    pub source_ids: Option<Vec<String>>,
    /// D-16: conversation-threading link. None for non-reply memories. (Phase 24.75 dropped
    /// the separate parent_id/chunking column; reply_to_id is the only threading link.)
    #[serde(default)]
    pub reply_to_id: Option<String>,
}

fn default_type_hint() -> String {
    "fact".to_string()
}

fn default_source() -> String {
    "default".to_string()
}

fn default_actor_type() -> String {
    "agent".to_string()
}

fn default_audience() -> String {
    "global".to_string()
}

/// Input type for partially updating an existing memory.
///
/// All fields are optional — only non-None fields are updated.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UpdateMemory {
    /// New content (optional)
    pub content: Option<String>,
    /// New type hint (optional)
    pub type_hint: Option<String>,
    /// New source (optional)
    pub source: Option<String>,
    /// New tags (optional, replaces existing tags)
    pub tags: Option<Vec<String>>,
    /// New trust level (optional). When set, produces a trust_history audit entry in metadata.
    pub trust_level: Option<f32>,
}

/// Filter criteria for listing memories with cursor-based pagination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListFilter {
    /// Filter by type_hint (exact match)
    pub type_hint: Option<String>,
    /// Filter by source (exact match)
    pub source: Option<String>,
    /// Filter memories created after this timestamp
    pub created_after: Option<DateTime<Utc>>,
    /// Filter memories created before this timestamp
    pub created_before: Option<DateTime<Utc>>,
    /// Filter memories updated after this timestamp
    pub updated_after: Option<DateTime<Utc>>,
    /// Filter memories updated before this timestamp
    pub updated_before: Option<DateTime<Utc>>,
    /// Maximum number of memories to return (default: 20, max: 100)
    pub limit: i64,
    /// Cursor from previous page for pagination
    pub cursor: Option<String>,
    /// Filter by actor (exact match, optional)
    pub actor: Option<String>,
    /// Filter by audience (exact match, optional)
    pub audience: Option<String>,
    /// Filter by project — returns project-scoped AND global (NULL project) memories.
    /// None means no project filter (return all regardless of project).
    pub project: Option<String>,
    /// Filter by session_id (exact match, optional).
    pub session_id: Option<String>,
    /// Filter by agent_role (exact match, optional).
    pub agent_role: Option<String>,
}

impl Default for ListFilter {
    fn default() -> Self {
        ListFilter {
            type_hint: None,
            source: None,
            created_after: None,
            created_before: None,
            updated_after: None,
            updated_before: None,
            limit: 20,
            cursor: None,
            actor: None,
            audience: None,
            project: None,
            session_id: None,
            agent_role: None,
        }
    }
}

/// Result of a list operation with optional pagination cursor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListResult {
    /// The retrieved memories
    pub memories: Vec<Memory>,
    /// Cursor for next page (None if no more results)
    pub next_cursor: Option<String>,
}

/// Filter criteria for vector similarity search with optional date and tag filters.
///
/// Keyset cursor-based pagination is supported via the `cursor` field (preferred).
/// OFFSET-based pagination is also supported via the `offset` field for backward compatibility,
/// but is deprecated and emits a tracing warning.
///
/// For search, the keyset cursor encodes (salience_score, id) pairs — see
/// `encode_search_keyset_cursor` / `decode_search_keyset_cursor` in this module.
#[derive(Debug, Clone)]
pub struct SearchFilter {
    /// The embedded query vector to search against (callers always set this explicitly)
    pub query_embedding: Vector,
    /// Maximum number of results to return (default: 20, max: 100)
    pub limit: i64,
    /// Number of results to skip for pagination (default: 0).
    /// DEPRECATED: Use cursor instead for new code.
    pub offset: i64,
    /// Opaque keyset pagination cursor (encodes salience_score + id from previous page).
    /// When set, `offset` is ignored (cursor takes precedence).
    pub cursor: Option<String>,
    /// Filter memories created after this timestamp
    pub created_after: Option<DateTime<Utc>>,
    /// Filter memories created before this timestamp
    pub created_before: Option<DateTime<Utc>>,
    /// Filter memories that have ALL specified tags (containment match)
    pub tags: Option<Vec<String>>,
    /// Filter by audience scope (optional)
    pub audience: Option<String>,
    /// Tier filter for search results. None = exclude "raw" by default (D-10).
    /// Some(vec!["all"]) = no filter. Some(vec!["raw","explicit",...]) = exact tier list.
    pub tier_filter: Option<Vec<String>>,
}

impl Default for SearchFilter {
    fn default() -> Self {
        SearchFilter {
            // Placeholder — callers always override query_embedding before use.
            // Length 1 avoids allocating a full-dimension vector for a non-meaningful default.
            query_embedding: Vector::from(vec![0.0f32; 1]),
            limit: 20,
            offset: 0,
            cursor: None,
            created_after: None,
            created_before: None,
            tags: None,
            audience: None,
            tier_filter: None,
        }
    }
}

/// A single search result containing the matched memory and its cosine similarity score.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchHit {
    /// The matched memory with all metadata
    pub memory: Memory,
    /// Cosine similarity score in [0.0, 1.0] — higher is more similar
    pub similarity: f64,
}

/// Paginated results from a vector similarity search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    /// The matched memories with similarity scores, ordered by similarity descending
    pub hits: Vec<SearchHit>,
    /// Total number of embedded memories matching the filters (ignoring limit/offset)
    pub total_matches: u64,
    /// Opaque pagination cursor for fetching the next page (None if no more results).
    /// Now encodes (salience_score, id) keyset pairs for stable pagination — decode with
    /// `decode_search_keyset_cursor` to inspect. Use as-is in the `cursor` parameter of
    /// SearchFilter or the CLI `--cursor` flag / MCP `cursor` param.
    pub next_cursor: Option<String>,
    /// Whether there are more results beyond the current page
    pub has_more: bool,
}

/// Encode a keyset search cursor from a salience score and memory id.
///
/// Format: base64url(json: {"t":"s","s":<score>,"i":"<id>"})
/// The type field "t":"s" marks this as a search cursor (vs "t":"l" for list cursors).
/// Server decodes transparently; clients treat the token as opaque.
pub fn encode_search_keyset_cursor(salience_score: f64, id: &str) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    let json = serde_json::json!({"t": "s", "s": salience_score, "i": id});
    URL_SAFE_NO_PAD.encode(json.to_string().as_bytes())
}

/// Decode a keyset search cursor back into (salience_score, id).
///
/// Returns `MemcpError::Validation` on malformed cursor or wrong cursor type.
pub fn decode_search_keyset_cursor(cursor: &str) -> Result<(f64, String), MemcpError> {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    let bytes = URL_SAFE_NO_PAD
        .decode(cursor)
        .map_err(|e| MemcpError::Validation {
            message: format!("Invalid search cursor encoding: {}", e),
            field: Some("cursor".to_string()),
        })?;
    let raw = String::from_utf8(bytes).map_err(|e| MemcpError::Validation {
        message: format!("Invalid search cursor content: {}", e),
        field: Some("cursor".to_string()),
    })?;
    let val: serde_json::Value =
        serde_json::from_str(&raw).map_err(|e| MemcpError::Validation {
            message: format!("Invalid search cursor JSON: {}", e),
            field: Some("cursor".to_string()),
        })?;

    // Verify type field is "s" (search cursor)
    let t = val.get("t").and_then(|v| v.as_str()).unwrap_or("");
    if t != "s" {
        return Err(MemcpError::Validation {
            message: format!("Invalid cursor type '{}': expected search cursor (t=s)", t),
            field: Some("cursor".to_string()),
        });
    }

    let score = val
        .get("s")
        .and_then(|v| v.as_f64())
        .ok_or_else(|| MemcpError::Validation {
            message: "Search cursor missing salience score field".to_string(),
            field: Some("cursor".to_string()),
        })?;
    let id = val
        .get("i")
        .and_then(|v| v.as_str())
        .ok_or_else(|| MemcpError::Validation {
            message: "Search cursor missing id field".to_string(),
            field: Some("cursor".to_string()),
        })?
        .to_string();

    Ok((score, id))
}

/// Encode a search pagination cursor from an offset value.
///
/// DEPRECATED: Use encode_search_keyset_cursor for new code.
/// Kept for offset backward compat — hybrid search still supports offset=N with
/// a deprecation warning; existing clients that decode offset cursors will continue
/// to work during the grace period.
pub fn encode_search_cursor(offset: i64) -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    URL_SAFE_NO_PAD.encode(offset.to_string().as_bytes())
}

/// Decode a search pagination cursor back into an offset value.
pub fn decode_search_cursor(cursor: &str) -> Result<i64, MemcpError> {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    let bytes = URL_SAFE_NO_PAD
        .decode(cursor)
        .map_err(|e| MemcpError::Validation {
            message: format!("Invalid search cursor encoding: {}", e),
            field: Some("cursor".to_string()),
        })?;
    let raw = String::from_utf8(bytes).map_err(|e| MemcpError::Validation {
        message: format!("Invalid search cursor content: {}", e),
        field: Some("cursor".to_string()),
    })?;
    raw.parse::<i64>().map_err(|_| MemcpError::Validation {
        message: "Invalid search cursor value".to_string(),
        field: Some("cursor".to_string()),
    })
}

/// Outcome of a store/persist operation. Enables callers (e.g. POST /v1/ingest)
/// to distinguish a newly inserted memory from a dedup hit (D-14).
#[derive(Debug, Clone)]
pub enum StoreOutcome {
    Created(Memory),
    Deduplicated(Memory),
}

impl StoreOutcome {
    pub fn into_inner(self) -> Memory {
        match self {
            Self::Created(m) | Self::Deduplicated(m) => m,
        }
    }
    pub fn memory(&self) -> &Memory {
        match self {
            Self::Created(m) | Self::Deduplicated(m) => m,
        }
    }
    pub fn was_deduplicated(&self) -> bool {
        matches!(self, Self::Deduplicated(_))
    }
}

/// Core abstraction for memory persistence operations.
///
/// All implementations must be Send + Sync to support concurrent access.
/// The trait uses async_trait to enable async methods in trait definitions.
#[async_trait]
pub trait MemoryStore: Send + Sync {
    /// Store a new memory and return a StoreOutcome distinguishing a newly
    /// inserted memory from a dedup hit (D-14). Canonical path for writes.
    async fn store_with_outcome(
        &self,
        input: CreateMemory,
    ) -> Result<StoreOutcome, MemcpError>;

    /// Store a new memory and return the created record.
    ///
    /// Provided default delegates to `store_with_outcome` and discards the
    /// outcome variant. Existing callers keep their Memory-returning shape.
    async fn store(&self, input: CreateMemory) -> Result<Memory, MemcpError> {
        Ok(self.store_with_outcome(input).await?.into_inner())
    }

    /// Retrieve a memory by ID.
    ///
    /// Also increments access_count and updates last_accessed_at via touch().
    async fn get(&self, id: &str) -> Result<Memory, MemcpError>;

    /// Update an existing memory (partial update).
    ///
    /// Only non-None fields in UpdateMemory are applied.
    async fn update(&self, id: &str, input: UpdateMemory) -> Result<Memory, MemcpError>;

    /// Delete a memory by ID.
    ///
    /// Returns NotFound error if the memory doesn't exist.
    async fn delete(&self, id: &str) -> Result<(), MemcpError>;

    /// List memories with optional filtering and cursor-based pagination.
    async fn list(&self, filter: ListFilter) -> Result<ListResult, MemcpError>;

    /// Count memories matching the given filter (for two-step bulk delete confirmation).
    async fn count_matching(&self, filter: &ListFilter) -> Result<u64, MemcpError>;

    /// Delete all memories matching the given filter.
    ///
    /// Returns the number of deleted memories.
    async fn delete_matching(&self, filter: &ListFilter) -> Result<u64, MemcpError>;

    /// Update last_accessed_at and increment access_count for a memory.
    ///
    /// Silently ignores if the ID doesn't exist (fire-and-forget semantics).
    async fn touch(&self, id: &str) -> Result<(), MemcpError>;
}

/// Infer a trust level from source and actor_type when not explicitly provided.
///
/// Trust scale: 0.0 (untrusted) to 1.0 (fully trusted).
/// - user-initiated or CLI stores: 0.8 (high — human in the loop)
/// - auto-store (sidecar): 0.3 (low — automated, may be noisy)
/// - import: 0.4 (low-moderate — bulk data, unknown quality)
/// - default: 0.5 (neutral)
pub fn infer_trust_level(source: &str, actor_type: &str) -> f32 {
    if actor_type == "user" || source == "cli" {
        return 0.8;
    }
    match actor_type {
        "auto-store" => 0.3,
        _ => match source {
            "import" => 0.4,
            _ => 0.5,
        },
    }
}
